development:
  adapter: mysql2
  database: myApp
  encoding: utf8  
  reconnect: false
  username: root 
  password: root
  pool: 5
  timeout: 5000
  
test:
  
  adapter: mysql2
  encoding: utf8  
  reconnect: false
  database: myApp
  username: root
  password: root
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8  
  reconnect: false
  database: myApp
  username: root
  password: root
  pool: 5
  timeout: 5000